### ISSUE TITLE
System Error 500 with [Upload] a file 

### ISSUE THREAD

**Issue by sgoodswen** [acadsamplesdb/acad_samples#17]
A System Error 500 is generated if you try to [Upload] a file that already exists

**Comment by craigpatten** [comment]
This is by design &mdash; for security reasons the application is not able to overwrite (or delete) data on the object store.  We could revisit this if required.

**Comment by sgoodswen** [comment]
I think the design is correct, but rather than a System Error 500 could we please inform the user that the file already exists and cannot be uploaded again 

OR 

Perhaps we can warn the user that the files already exists but also give the option to replace it

**Comment by sgoodswen** [comment]
fixed
