### ISSUE TITLE
[Add Sample] generates System Error 500

### ISSUE THREAD

**Issue by sgoodswen** [acadsamplesdb/acad_samples#18]
The [Add Samples] option now terminates with the usual System Error 500 regardless of the field entries.

**Comment by Li-ReDBox** [comment]
@sgoodswen:  Do we know if all issues of 500 error are related? Here are the others: #13, #17

**Comment by franksc** [comment]
Running the app in debug mode (DEBUG=True in Django settings.py) should provide stack trace-type error messages, rather than inscrutable 500s.

**Comment by sgoodswen** [comment]
fixed
