### ISSUE TITLE
Prevent letters in GP numbers

### ISSUE THREAD

**Issue by sgoodswen** [acadsamplesdb/acad_samples#20]
[Add sample group] and [Upload Samples] allows letters in GP numbers.

For example, GPO13  (i.e. letter O entered instead of a zero). 

Also, in [Add sample group] if a user enters GP and then a number e.g GP001 the Group number created is GPGP 001

**Comment by Li-ReDBox** [comment]
In  [Upload Samples],  do you want to strip out all letters and only grab numbers in the cell? If so, "GPO13" will be "13", "GP001" will be "001". But I have seen some group names are like "GP0518 Bone (Poland)". Please advice what pattern do you want.

In [Add sample group] form, Group is a dropdown list. Is there another field allows free text?

**Comment by Li-ReDBox** [comment]
Only allow number for [Group number] field and no prefix is allowed.
In form [/samplegroup/add/], only allow number in [Group number] field.
In csv upload function, same rule apply and display error message and stop uploading.

**Comment by sgoodswen** [comment]
This issue has been fixed
