### ISSUE TITLE
DNA yield in Extraction results needs 2 decimal places

### ISSUE THREAD

**Issue by sgoodswen** [acadsamplesdb/acad_samples#21]
In the Lab extractions tab when entering sample details you are only able to enter a whole number for DNA yield.  Please change this to accept up to 2 decimal places.

**Comment by Li-ReDBox** [comment]
[DNA yield](https://github.com/acadsamplesdb/acad_samples/blob/master/samples/models.py#L153) is defined as PositiveIntegerField. The proposed change will change the database scheme.

**Comment by sgoodswen** [comment]
This also a problem in the Lab Amplification tab when entering extraction result details you are only able to enter a whole number for DNA yield. Please change this to accept up to 2 decimal places.

**Comment by Li-ReDBox** [comment]
If we use [decimalfield](https://docs.djangoproject.com/en/1.8/ref/models/fields/#decimalfield), you have to define the maximal allowed digits. How many do you want?

**Comment by sgoodswen** [comment]
5 digits e.g. 000.00  (i.e. 3 digits before 2 decimal places)

**Comment by Li-ReDBox** [comment]
Do you want dna yield EnrichmentResult to be changed to decimal type too?

**Comment by Li-ReDBox** [comment]
EnrichmentResult should also be changed for consistence after discussion.

**Comment by sgoodswen** [comment]
If you enter more than 2 decimal places the program correctly warns with a "Please select a valid value" message. However, if more than 3 digits precede the decimal point e.g. 1000 or 1000.33 no message is displayed (although the program correctly does not respond to the [submit] button).

**Comment by Li-ReDBox** [comment]
I used Firefox and Chromium and I had error message. This one is of them:
![screenshot from 2016-03-31 12 03 40](https://cloud.githubusercontent.com/assets/3203171/14163116/ab0f3ee4-f739-11e5-8fc5-1ceb2bb044e9.png)

Did you use Safari? I have not changed any error handling which is from the base library. Have you seen any error messages before in any forms?

**Comment by sgoodswen** [comment]
I am using Firefox 45.0.1 on a Mac. For the DNA yield I only see this type of error:

![screen shot 2016-03-31 at 1 31 58 pm](https://cloud.githubusercontent.com/assets/16111098/14164222/22222d92-f745-11e5-828a-9e60322a4b7f.png)

**Comment by Li-ReDBox** [comment]
@sgoodswen it looks like a reasonable response even it is not in red. Not sure why it has different colours for errors.

**Comment by sgoodswen** [comment]
I still do not get an error if more than 3 digits precede the decimal point e.g. 1000 or 1000.33

**Comment by Li-ReDBox** [comment]
If you cannot save changes with invalid data, that means validation works. If you cannot save but you cannot see error message, and it happens in majority browsers, then we have to do more tests and maybe finish this later given the limited available time .

**Comment by sgoodswen** [comment]
I confirm that you cannot save changes with invalid data e.g. 1000 or 1000.33, and this is what we want. However, for the record I do not see any error messages when using a Mac and Firefox, Windows 7 and Firefox, or Windows 7 and Internet explorer 11 when entering either1000 or 1000.33
I also confirm that the actual reported issue .i.e. “DNA yield in Extraction results needs 2 decimal places” has been fixed and therefore this issue can be closed

**Comment by Li-ReDBox** [comment]
Thank @sgoodswen very much for doing the confirmations on different browsers. It is bad that user could not get good response if using certain browsers but at least the software does not allow un-wanted data pass.

**Comment by sgoodswen** [comment]
This issue has been fixed
