### ISSUE TITLE
Add visual indicator of samples [ACAD #2]

### ISSUE THREAD

**Issue by Li-ReDBox** [acadsamplesdb/acad_samples#22]
Add visual indicator of whether a sample has been:
1. extracted
2. had a library made (Amplification?)
3. Enrichment
4. been sequenced

**Comment by Li-ReDBox** [comment]
[Currently](https://github.com/acadsamplesdb/acad_samples/blob/master/samples/templates/sample/sample_table.html#L22), 
1. red start is used for "has been extracted" 
2. blue start is used for "is_carbondated" 

@sgoodswen, could you please:
1. verify if the above four items to be included in displaying indicators; 
2. clarify the question mark; 
3. confirm if red and blue starts should be used as current and
4. pick what symbols to use. The symbols can be choose from [here, currently used](http://getbootstrap.com/components/#glyphicons) or any other sets you can find.

**Comment by sgoodswen** [comment]
1.  extracted  <- this is currently a red star
2.  had a library made (Amplification?)  <- Yes, for Amplification: symbol = glyphicon glyphicon-plus (green)
3.  has Enrichment (?) <- Yes, for Enrichment : symbol = glyphicon glyphicon-play-circle (magenta)
4.  been sequenced  <- Yes, for sequencing: symbol = glyphicon glyphicon-ok (black)

Yes, please continue to use red and blue stars as is current

Is it possible to have a legend on the Samples selection page please?

**Comment by Li-ReDBox** [comment]
Thanks @sgoodswen.

Could you please clarify _"Is it possible to have a legend on the Samples selection page please?"_ 

Thanks

**Comment by sgoodswen** [comment]
On the Samples page (https://upload-fix.oagr.org.au/sample/) in the blank space on the right hand side, please have the following:

(Red star)      Extraction
(Green plus)        Amplification
(Magenta circle)    Enrichment 
(Black ok symbol)   Sequencing
(Blue star)     Carbon dated        

Within the brackets you would place the actual coloured symbol

**Comment by Li-ReDBox** [comment]
@sgoodswen, could you please create some testing dataset which has all these linked data?

**Comment by sgoodswen** [comment]
Sample 2 now has an extraction, amplification, Enrichment, Sequencing and Carbon dating (we should see 5 coloured symbols)
Sample 7 has extraction, amplification, Enrichment (we should see 3 coloured symbols)

**Comment by Li-ReDBox** [comment]
Thanks @sgoodswen

**Comment by Li-ReDBox** [comment]
@sgoodswen ,  could you please help me to understand [sequence model](https://github.com/acadsamplesdb/acad_samples/blob/master/samples/models.py#L200)? It seems to me is a method description: what amplification and enrichment methods are used. I have not found links to any results.

**Comment by sgoodswen** [comment]
Sorry Li, not sure what you mean by “sequence model”. 

Sample ID 2 is linked to Extractions, Amplifications, Enrichments and Sequences 

To find the links to the results for Sample 2 select ‘Extraction 2016-01-22 steve”. You will see extraction result 2A.

Select “Amplification 2016-01-29 stephen” and you will see Amplification results for 2A_2, 2A_1, 7A_1. 

Select “Enrichment 2016-01-29 harry” and you will see Enrichment results for 2A_1a and 2A_2a

Hopefully the following will help explain how  the IDs link together.

There is a hierarchical relationship between the Sample ID and the Lab options:

Extractions -> New extraction  (no ID is given)

```
Extraction results -> [+]
    Add a result … enter a Sample ID e.g. 444
```

Note: 1 extraction can have 0 to 1 extraction results (linked to sample IDs). Extraction result ID uses the sample ID + an incremental uppercase letter commencing from A e.g. Sample ID = 444 -> Extraction result ID = 444A

Amplifications -> New amplification (no ID is given) [Mandatory: Date, Prepared by, Method]

```
Amplification results -> [+]
```

Add a result … enter a Extraction result ID e.g. 444A

Note: Amplification result ID uses the Extraction result ID + an incremental number commencing from 1 e.g. Extraction result ID = 444A -> Amplification result ID = 444A_1

Enrichments -> New enrichment (no ID is given) [Mandatory: Date, Prepared by]

```
Enrichment results -> [+]
```

Add a result … enter an Amplification result ID = 444A_1

Note: 1Enrichment can have 0 to 1 Enrichment results. Enrichment result ID uses the Amplification result ID + an incremental lowercase letter commencing from a e.g. Amplification result ID = 444A_1 -> Enrichment result ID = 444A_1a

Sequencing -> New sequencing

```
Select Amplification and Enrichment from drop down boxes
```

**Comment by Li-ReDBox** [comment]
I think I was on the correct direction: Sequencing does not link to Amplification results or Enrichment results. If you could confirm, or clarify more in case you cannot confirm, will be good.

**Comment by sgoodswen** [comment]
Yes you are correct ,it does not link to the Amplification "results" or Enrichment "results" but is linked to either an Amplification or Enrichment title e.g. a path name to a sequence file is linked to "Sequence for Amplification 2016-01-29 Stephen" in the test database

**Comment by sgoodswen** [comment]
Sample 2 has both Amplification and Enrichment and 7 only has
Amplification as you said.

We need to show sequencing symbol if a sample is associated with  an Amplification OR an Enrichment OR both

**Comment by Li-ReDBox** [comment]
I have made it as OR and now 7 has OK label shown.

**Comment by sgoodswen** [comment]
I agree, everything is now displayed as expected.

**Comment by sgoodswen** [comment]
We still need a legend for the symbols please

**Comment by Li-ReDBox** [comment]
Could you please let me know if I have it is as you wanted? See it on the dev site.

**Comment by sgoodswen** [comment]
If you could please remove the words  "Red star, Green plus etc.. " and only have the symbol

**Comment by Li-ReDBox** [comment]
I have removed my debug strings to make it more production like. I have check in Firefox and Chromium on a high def screen. Hopefully it looks ok in others.

**Comment by sgoodswen** [comment]
It looks good.

I think this issue can now be closed ... thanks
