### ISSUE TITLE
Hierarchical list of links to sample's extractions, amplifications, and enrichments [ACAD # 8]

### ISSUE THREAD

**Issue by Li-ReDBox** [acadsamplesdb/acad_samples#24]
Enhancement ID: 8
When a Sample is selected it needs to provide hierarchical list of links to its extractions, amplifications, and enrichments.

**Comment by Li-ReDBox** [comment]
@sgoodswen, currently on detail page of a sample, it only lists Extraction and Carbon date. 

Just to confirm with you that:
1.Amplification and Enrichment are needed to be added to detail page
2. How do you want amplifications and enrichments to be displayed? Is indentation OK? e.g.:
    Extraction
         Amplification
              Enrichment
   above Carbon date?

**Comment by sgoodswen** [comment]
Yes, on the detail page of the sample we need to list inks to all children. Similar to what is currently displayed for Extraction and Carbon date.

Yes, indentation is OK for the lab options e.g.
  Extraction link
          Amplification link
                 Enrichment link
                     Sequencing link
Carbon date (no indentation)

**Comment by Li-ReDBox** [comment]
Would you be able to have a look at samples 2, 7 and other on dev site?

**Comment by sgoodswen** [comment]
How you display the links looks good. The correct links are also displayed. However, if I select an amplification or enrichment link I get an error:

ValueError at /amplification/2A_2/

invalid literal for int() with base 10: '2A_2'

Request Method:     GET
Request URL:    http://upload-fix.oagr.org.au/amplification/2A_2/
Django Version:     1.8.2
Exception Type:     ValueError
Exception Value:    

invalid literal for int() with base 10: '2A_2'

Exception Location:     /data/samples/venv/lib/python3.4/site-packages/django/db/models/fields/**init**.py in get_prep_value, line 985
Python Executable:  /data/samples/venv/bin/python
Python Version:     3.4.3
Python Path:    

['/data/samples',
 '/data/samples/venv/lib/python3.4',
 '/data/samples/venv/lib/python3.4/plat-x86_64-linux-gnu',
 '/data/samples/venv/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/data/samples/venv/lib/python3.4/site-packages']

Server time:    Wed, 3 Feb 2016 10:25:37 +1030

**Comment by Li-ReDBox** [comment]
Seems it should point to Amplification not AmplificationResult, same to Enrichment. I will change it

**Comment by Li-ReDBox** [comment]
Sample 2 has two AmplificationResults which all point to the same Amplification. As you asked only display Amplification, there is only one entry. Same to Enrichment. Is this correct? You can see it on the page.

**Comment by sgoodswen** [comment]
I believe this is correct
