### ISSUE TITLE
Error when adding new permit and the "Active from" field is blank

### ISSUE THREAD

**Issue by sgoodswen** [acadsamplesdb/acad_samples#26]
IntegrityError at /permit/add/

null value in column "active_from" violates not-null constraint
DETAIL:  Failing row contains (3, 2, 2016-02-10, 2016-02-10, 30, null, , ).

Request Method:     POST
Request URL:    http://upload-fix.oagr.org.au/permit/add/
Django Version:     1.8.2
Exception Type:     IntegrityError
Exception Value:    

null value in column "active_from" violates not-null constraint
DETAIL:  Failing row contains (3, 2, 2016-02-10, 2016-02-10, 30, null, , ).

Exception Location:     /data/samples/venv/lib/python3.4/site-packages/django/db/backends/utils.py in execute, line 64
Python Executable:  /data/samples/venv/bin/python
Python Version:     3.4.3
Python Path:    

['/data/samples',
 '/data/samples/venv/lib/python3.4',
 '/data/samples/venv/lib/python3.4/plat-x86_64-linux-gnu',
 '/data/samples/venv/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/data/samples/venv/lib/python3.4/site-packages']

Server time:    Wed, 3 Feb 2016 14:23:44 +1030

**Comment by Li-ReDBox** [comment]
@sgoodswen, could you please check if the problem of that field has been fixed?

**Comment by Li-ReDBox** [comment]
Replaced by #35
