### ISSUE TITLE
Selecting samples on multiple pages does not work

### ISSUE THREAD

**Issue by Li-ReDBox** [acadsamplesdb/acad_samples#28]
This was mentioned as a part of enhancement id 6:
Make a project only works on one page. This needs to work when selecting on multiple page.

**Comment by Li-ReDBox** [comment]
@sgoodswen I have had a very rough set-up on the dev site only for selecting.  You may be able to select samples on different pages. Partially worked for me. But still work to be done mainly when moving around, things might not correctly displayed and etc. On server side, nothing has been done yet: so you can not, for example, export samples on different pages, yet.

Also be aware of browser compatibility of old IEs.

I am not sure if I have understood the user cases, so there is no guarantee the implementation has met the requirement.

**Comment by Li-ReDBox** [comment]
The requirement changed to make a form with search ability for adding samples to a list for exporting or making a project.

**Comment by Li-ReDBox** [comment]
files to be changed to enable building a list on client side var search:
1. https://github.com/acadsamplesdb/acad_samples/blob/master/samples/views.py#L874
2. https://github.com/acadsamplesdb/acad_samples/blob/master/samples/templates/search/search.html
3. https://github.com/acadsamplesdb/acad_samples/blob/master/acad_samples/urls.py#L102
4. http://django-haystack.readthedocs.org/en/latest/searchresult_api.html#get-stored-fields

**Comment by sgoodswen** [comment]
The changes made to the Search menu to allow multiple samples to be selected is an acceptable solution. This issue can be closed once tested in production

**Comment by Li-ReDBox** [comment]
@sgoodswen do you want keep the issue open but deployed to production server?

**Comment by sgoodswen** [comment]
I would like to keep all the issues that you have fixed and deployed to production 'open' please, and then I will close them once I have tested them in production ... thanks

**Comment by Li-ReDBox** [comment]
@sgoodswen no problems. I have put close command into commits in other fixes as I always do because I was not aware this is a requirement. I will leave them as they are. If you find some issues were closed by commits, feel free to reopen them.

**Comment by sgoodswen** [comment]
The solution has been implemented correctly in production
