### ISSUE TITLE
Cannot delete an Extraction result

### ISSUE THREAD

**Issue by sgoodswen** [acadsamplesdb/acad_samples#30]
You cannot delete an extraction result using the red delete button (although it still prompts "are you sure you want to delete")

**Comment by Li-ReDBox** [comment]
Fix is covered by #31 and code is [here](https://github.com/acadsamplesdb/acad_samples/commit/86143267b6c5329ed3320653d5cede004a5b9f55#diff-35cff2ba5cc2c7450c1f8f2adfa2dbd1R126)

**Comment by sgoodswen** [comment]
This issue has been fixed and tested for Extraction, Amplification, and Enrichment results
