### ISSUE TITLE
"Active from" field in New Permit needs to be mandatory 

### ISSUE THREAD

**Issue by sgoodswen** [acadsamplesdb/acad_samples#35]
"Active from" field in New Permit  needs a \* to indicate that it is a mandatory field
e.g. Active from*

If this field is left blank you get the following error:

integrityError at /permit/add/

null value in column "active_from" violates not-null constraint
DETAIL:  Failing row contains (8, 27, 2016-03-03, 2016-04-06, 45, null, , ).

Request Method:     POST
Request URL:    http://upload-fix.oagr.org.au/permit/add/
Django Version:     1.8.2
Exception Type:     IntegrityError
Exception Value:    

null value in column "active_from" violates not-null constraint
DETAIL:  Failing row contains (8, 27, 2016-03-03, 2016-04-06, 45, null, , ).

Exception Location:     /data/samples/venv/lib/python3.4/site-packages/django/db/backends/utils.py in execute, line 64
Python Executable:  /data/samples/venv/bin/python
Python Version:     3.4.3
Python Path:    

['/data/samples',
 '/data/samples/venv/lib/python3.4',
 '/data/samples/venv/lib/python3.4/plat-x86_64-linux-gnu',
 '/data/samples/venv/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/data/samples/venv/lib/python3.4/site-packages']

Server time:    Wed, 2 Mar 2016 10:08:31 +1030

**Comment by Li-ReDBox** [comment]
Replace #26

**Comment by Li-ReDBox** [comment]
To make migration simpler, it has default `null=True`

**Comment by sgoodswen** [comment]
If you do not enter an "Active from" the program correctly displays in red "This field is required". However, if you then select an "Active from" the program incorrectly still displays in red "This field is required" (see attached screenshot).

![screen shot 2016-03-30 at 5 05 45 pm](https://cloud.githubusercontent.com/assets/16111098/14160889/10d64686-f727-11e5-88ef-2e927a3dafe9.png)

**Comment by Li-ReDBox** [comment]
What version of Safari are you using?

**Comment by sgoodswen** [comment]
I am using Firefox 45.0.1 on a Mac.

If I use [submit], it creates the permit OK with no errors.

**Comment by Li-ReDBox** [comment]
I now get what you were looking for. I doubt it has the ability to monitor change to clear error message on client side. I think it does the check on server side.

**Comment by sgoodswen** [comment]
The fact that the it still displays in red "This field is required"  when a value is entered is minor issue and more cosmetic . Otherwise this issue is fixed.
