### ISSUE TITLE
"Permit number" field is not automatically populated in New sample group 

### ISSUE THREAD

**Issue by sgoodswen** [acadsamplesdb/acad_samples#36]
If a permit is selected from the Permit drop down box in  [Add sample Group], the selected permit number should automatically populate the “Permit number” field.

**Comment by sgoodswen** [comment]
There are two Permit fields when adding a samples group: Permit [a dropdown box] and Permit Number [a free text box]. This is confusing to users and the ‘free text’ is prone to mistakes.

The display is composed of 3 parts in the dropdown box,:  Permit number, Valid for, and Valid to e.g. 200507186 Soil (valid to 2007-05-05)

The proposed solution is to make the Permit number field 'read only' and display only the Permit number e.g. 200507186  that is selected in the drop down box.

In effect we only have one field for the user to select the Permit number and that is from the dropdown.

**Comment by Li-ReDBox** [comment]
The model itself is also confusing. Anyway, a javascript fix has been implemented. 
@sgoodswen could you please have a look?

**Comment by sgoodswen** [comment]
The program correctly displays the permit number when selecting from the dropdown box, but incorrectly does not retain the permit number in the "Permit number" field after the [Submit] button is selected

![screen shot 2016-03-31 at 12 02 56 pm](https://cloud.githubusercontent.com/assets/16111098/14162998/9507047a-f738-11e5-9fce-13ee93f240f0.png)

**Comment by Li-ReDBox** [comment]
@sgoodswen  Can you check it again?

**Comment by sgoodswen** [comment]
This issue has been fixed and tested in the development version of SamplesDB
