### ISSUE TITLE
Buttons to appear at top and botton of  page [ACAD #21]

### ISSUE THREAD

**Issue by sgoodswen** [acadsamplesdb/acad_samples#40]
Buttons to appear at top and bottom of  page when there is a long list of items on a page

e.g. In the extractions page to have [Add extraction] at the top of page in addition to the one that currently appears at the bottom (this saves on scrolling to the bottom of page)

**Comment by sgoodswen** [comment]
This issue is considered to be a flaw in the initial design of the web pages.

The solution is to move the option buttons e.g.  [Add sample group] [Upload sample group] to the top of the web page only if the page content is longer than the page height.  Ideally, for long pages it would be beneficial to have the same set of buttons at both the top and bottom of the page.

This solution is required for the following menu options:

Samples
Carbon dates
Quarantine sample groups
Permits

Extractions
Amplifications
Enrichments
Sequencing

**Comment by Li-ReDBox** [comment]
amplification/index.html
c14/index.html
enrichment/index.html
extraction/index.html
permit/index.html
sample/index.html
samplegroup/index.html
sequence/index.html

have been changed to meet the requirements. Page height depends on resolution of a screen not easy to detect on server side so I propose to use row number as the criterion. The default value used on sample page to control pagination is 100, so I think 100 is a reasonable number. Currently, for testing purpose, it is set to be 10. When the number of rows above 10, buttons will appear at both top and bottom. This number is a configurable item can be changed by sysadmin in settings.py.

Please bear in mind, THIS IS A VERY UGLY fix and should be considered as temporary. More than this will require significant time.

Also, user can use HOME and END with or without Ctrl key or similar keys to jump to top or bottom of a page.

**Comment by sgoodswen** [comment]
We are happy with this fix and leaving the  default for the number of rows at 10 has been requested by the main users.

**Comment by sgoodswen** [comment]
This issue can be closed
