### ISSUE TITLE
Change list order for extractions and amplifications

### ISSUE THREAD

**Issue by sgoodswen** [acadsamplesdb/acad_samples#41]
For Extractions, order of the extractions listed on the page based on the "Date extracted" i.e. newest date extracted at top of page 

For Amplifications, order of the amplifications listed on the page based on the "Date" (newest date at top of page)

**Comment by Li-ReDBox** [comment]
@sgoodswen could you have a check?

**Comment by sgoodswen** [comment]
I confirm that this issue has been fixed and can be closed
