### ISSUE TITLE
Only an Admin user should be able to delete a sample

### ISSUE THREAD

**Issue by sgoodswen** [acadsamplesdb/acad_samples#42]
Currently, a normal user can delete a Sample if there are no children i.e. extractions, amplifications, and an Admin user can delete a sample with or without children. We would like to remove the [Delete me] button for a normal user when editing a sample. That is, only an Admin user can delete a sample whether it has children or not. A normal user can then only change field values when editing a sample but can’t delete it.

**Comment by Li-ReDBox** [comment]
A [change](https://github.com/acadsamplesdb/acad_samples/commit/5a0c012782bd9c9283c4d10b67d7e3a552c558d6) has been made on dev and can be made to production any time if passed tests.

**Comment by sgoodswen** [comment]
This issue has been fixed and tested on dev and is ready for release to production

**Comment by Li-ReDBox** [comment]
Production site has been updated.

**Comment by sgoodswen** [comment]
This issue has been tested in production and can be closed
