### ISSUE TITLE
Carbon dates decimals issue in samples

### ISSUE THREAD

**Issue by jsoubrier** [acadsamplesdb/acad_samples#45]
In https://samples.oagr.org.au/c14/, the values look good (only a few decimals, as uploaded from the speadsheet).
However, in https://samples.oagr.org.au/sample/1/, for example, at the bottom of the page, most values for Carbon Dates have lots of decimals (e.g., 19.89999999999999857891), which seems to be a made up number as this amount of decimals was never in our uploaded data.
![screen shot 2016-04-05 at 2 43 18 pm](https://cloud.githubusercontent.com/assets/5704915/14271891/c8a1f9c2-fb3c-11e5-86f9-a751f3e262a9.png)

**Comment by Li-ReDBox** [comment]
In the model of c14, they have very high precision: [20 decimal places](https://github.com/acadsamplesdb/acad_samples/blob/master/samples/models.py#L350)

**Comment by jsoubrier** [comment]
Does that mean the program 'makes up' decimals when they are absent for displaying on the samples page?
Can we simply reduce that to 2 decimals for clarity?
Thanks!

**Comment by Li-ReDBox** [comment]
I will have some investigation to see where the problem is. I am not sure if it is a display problem. Of course, if no high accuracy is required, I can convert them into another type.

**Comment by jsoubrier** [comment]
Thing is, I don't think we ever had this number of decimals to start with... Here is what has been uploaded to the C14 table (original data - sample 1 is the same example as above):
![screen shot 2016-04-07 at 09 58 49](https://cloud.githubusercontent.com/assets/5704915/14336866/7effd548-fca7-11e5-90fc-4bfd5d7d6178.png)

The display on the C14 page of the database looks good and reflects the original data input:
![screen shot 2016-04-07 at 10 01 56](https://cloud.githubusercontent.com/assets/5704915/14336923/fc0d040c-fca7-11e5-9645-17e1a2026224.png)

If we could display exactly the same on the sample page (without the 25 decimals) it would be perfect, otherwise, just fixing it at 2 decimals would do the trick for us :-)

Cheers!

**Comment by Li-ReDBox** [comment]
Follow up: 
index page of C14 uses a [display conversion filter](https://github.com/acadsamplesdb/acad_samples/blob/master/samples/templates/c14/index.html#L41) which hides when these decimal numbers are precision loose.

I applied this conversion on sample's detail page.

Please check if it has fixed the problem.

**Comment by jsoubrier** [comment]
Working great!
Thanks Li
