### ISSUE TITLE
Search issues

### ISSUE THREAD

**Issue by jsoubrier** [acadsamplesdb/acad_samples#47]
Searching for a number works (e.g., 885) but not for a keyword (e.g., bison). Difficult to say if the algorithm is running and taking a long time, or just not working.

Also, clicking on the column names to sort (increasingly or decreasingly) is not working.

**Comment by Li-ReDBox** [comment]
The function works as expected. The reason of being slow is because of the number of hit is too high. 

There was a problem of sorting. I have implemented a solution on the test server. If you could have a look and let me know if it works as you expected, I will move it to the production server.

**Comment by jsoubrier** [comment]
Hi Li,
Yes the sorting is working well on the test server.
Thanks for checking the search function. Is there any way to display a message when the search is complete but did not find any match? At the moment, it is not possible to tell if still running or finished running with no hit.
Cheers,
Ju

**Comment by Li-ReDBox** [comment]
The simple way to do is to display "No result found" message. I put it in action on test server. Let me know what you think.

**Comment by jsoubrier** [comment]
Looks great thanks!
Also, is it normal that a new search just adds results at the bottom of the previous search results (VS doing a new clean search)?
Ju

**Comment by Li-ReDBox** [comment]
Great. 

It is designed to not remove previous search results. This just reminded me of using search to create a collection for exporting samples to csv. Apparently, it is not working. :cry:

**Comment by Li-ReDBox** [comment]
@jsoubrier it was a false alarm at least I think it is: I did not tick any checkboxes. No wonder nothing exported. Could you please confirm if it is the case?

**Comment by jsoubrier** [comment]
Yes, at the moment we've got an empty table (header only) when exporting from search (either test or current server)

**Comment by Li-ReDBox** [comment]
I did another one on production server from the search of 'bison OR pig' and in the exported csv it has 1776 rows. Last time I reported the problem because I did not tick the checkboxes in front of each sample row.

**Comment by jsoubrier** [comment]
Sorry I misunderstood your point... Yes, it works and exports the csv!
Ju

**Comment by Li-ReDBox** [comment]
That's good nothing to worry. I will put this sorting fix to production server.
