### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by jsoubrier** [acadsamplesdb/acad_samples#48]
Nothing happens when conducting a search at https://samples.oagr.org.au/search/
No error message or loading.

**Comment by Li-ReDBox** [comment]
@jsoubrier I only got a chance to check the migrated system. The service was not running well and it seems running now. Would you be able to have a look to confirm if it works?

**Comment by jsoubrier** [comment]
@Li-ReDBox Yes search works now, thanks!

**Comment by Li-ReDBox** [comment]
@jsoubrier that is good.
