### ISSUE TITLE
C14 database not working

### ISSUE THREAD

**Issue by jsoubrier** [acadsamplesdb/acad_samples#49]
https://samples.oagr.org.au/c14/ is returning the following: "Server Error (500)"

**Comment by Li-ReDBox** [comment]
Could you please do a quick check if it works now after elasticsearch is working? These two appear not linked but just in case there is something I don't know. I can run shell fine.

**Comment by jsoubrier** [comment]
No, I had a look already, still getting the error 500...

**Comment by Li-ReDBox** [comment]
One of centre's name has space in it: xxx xxxx, which causes SlugField generated in-suitable url.

**Comment by Li-ReDBox** [comment]
After I did an urgent fix, the page can be loaded. Please let me know if you can confirm. I will commit a proper fix if the urgent fix is acceptable.

**Comment by jsoubrier** [comment]
Yes, working well at the moment

**Comment by Li-ReDBox** [comment]
Good to hear. Let's hope it will stay that way.

**Comment by jsoubrier** [comment]
Thanks for fixing the C14 sheet!
Is there any chance you could rename the field 'Sample Reference' to 'Other ID' and make it non-mandatory?
Also, could we add an extra free-text field called 'Notes'? That would be extremely useful.
Cheers,
Ju

**Comment by Li-ReDBox** [comment]
I moved rename and notes field to another issue #51
